### ISSUE TITLE
websocket not working.

### ISSUE THREAD

**Issue by clock157** [deepstreamIO/docker#4]
websocket function not working with the base mhart/alpine-node:4.
`deepstream('localhost:6020').login()`
i change it to centos:7,it works well.

**Comment by RobTS** [comment]
Same here.

**Comment by yasserf** [comment]
Hey, @PhillippOhlandt has created a few new docker images. They run the binaries/not node and are going to be auto generated with releases. Will update once this is done

**Comment by PhillippOhlandt** [comment]
Hey @clock157, the new Docker image is available since yesterday. https://hub.docker.com/r/deepstreamio/deepstream.io/ It's based on CentOS 7. You probably have to adjust your mounted folders and the `libDir` + log location inside your config.yml

**Comment by clock157** [comment]
thanks,@yasserf  @PhillippOhlandt  :)
